### ISSUE TITLE
You must provide inputs *items_to_send* and/or *items_to_receive*

### ISSUE THREAD

**Issue by siriate** [karer/node-wax-expresstrade#7]
I'm trying to send a simple offer yet, there is an error:

```
API.ITrade.SendOffer({
  items_to_send: [233223],
  uid: 5993384,
  token: "SRiahILo"
})
  .then(data => {
    console.log(data);
  })
  .catch(err => {
    console.log(err.message);
  });

```

Error i get: `400 - {"status":312,"time":1548103492,"message":"You must provide inputs *items_to_send* and/or *items_to_receive*"}`

**Comment by karer** [comment]
Please use `itemsToSend` (camelCase)
